me: Terraform

on:
   push:
    branches:
    - main
   pull_request:
    branches:
    - main
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

# Checkout the repository to the GitHub Actions runner
  steps:
  - name: Checkout
    uses: actions/checkout@v2